### ISSUE TITLE
Missing top level package.json file

### ISSUE THREAD

**Issue by pelegri** [alexziskind1/nativescript-calculator-demoapp#1]
I tried running the sample.  I'm using the latest {N}, 1.1.  THe emulator ran fine but when I tried on an actual device I got an error.  THe problem was in the Info.plist.  The dummy value for the key CFBundleIdentifier had not been properly replaced with the actual value.  The .tnsproject file has the proper value but I believe this is nowadays done from the value of "id" in the top-level package.json file.

I added the value and it now works.

I'm not including a pull reques as I don't know if you think the .tnsproject file should be removed or left there.

**Comment by alexziskind1** [comment]
Thanks for pointing this out. I've update the project to the latest version (now 1.1.2) and tested on the emulator and device.
